name: ShiftDistance
version: ${project.version}
main: net.teamfruit.shiftdistance.ShiftDistance
api-version: 1.15
authors: [Kamesuta]

commands:
  shiftdistance:
    aliases:
      - sd
    usage: /sd <radius>
    description: 半径を設定
    permission: shiftdistance.set
    permission-message: 権限がないよ～

permissions:
  shiftdistance.set:
    description: 半径を設定する
    default: op
  shiftdistance.use:
    description: 機能を使う
    default: true
